#ifndef ALICE2_USER_SKETCH_H
#define ALICE2_USER_SKETCH_H

#include "ISketch.h"

namespace alice2 {

    // Forward declarations for user sketch functions
    // These are generated by the ALICE2_REGISTER_SKETCH macro in userSrc/sketch_base.cpp
    extern "C" {
        ISketch* createSketch();
        void destroySketch(ISketch* sketch);
        const char* getSketchName();
    }

} // namespace alice2

#endif // ALICE2_USER_SKETCH_H
